/* This file is generated by util/getversion.sh */
/* Version string for use by common/version.c */
#define CROS_EC_VERSION "bob_v1.1.5705-45cf222"
/* Version string, truncated to 31 chars (+ terminating null = 32) */
#define CROS_EC_VERSION32 "bob_v1.1.5705-45cf222"
/* Sub-fields for use in Makefile.rules and to form build info string
 * in common/version.c. */
#define VERSION "bob_v1.1.5705-45cf222"
#define BUILDER "henrysun@henrysun.sha.corp.google.com"
/* Repo is clean, use the commit date of the last commit */
#define DATE "2019-12-16 09:58:20"
